apiVersion: openfaas.com/v1alpha2
kind: Function
metadata:
  name: expenseemailsender
spec:
  name: expenseemailsender
  image: __IMAGE__
  imagePullSecrets:
  - name: regcred
  environment:
    write_debug: "true"
    SENDGRID_API_KEY: "__SENDGRIDAPIKEY__"
  secrets:
      - regcred
  annotations:
    topic: "nats-email"